site_name: My Docs
nav:
  - kurssi.md
  - johdanto.md
  - 'Paikallinen Git':
    - peruskaytto.md
    - haarat.md
  - 'Hajautettu Git':
    - etarepositoriot.md
    - hosting_palvelut.md
  - versionhallinta_projektissa.md
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
