site_name: Git-versionhallinta
nav:
  - johdanto.md
  - 'Paikallinen Git':
    - peruskaytto.md
    - haarat.md
  - 'Hajautettu Git':
    - etarepositoriot.md
    - hosting_palvelut.md
  - versionhallinta_projektissa.md
  - muita_toimintoja.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      title: Sisällysluettelo
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

